export const THEMES = [
  {
    name: 'skyrim',
    label: 'Skyrim',
    emoji: '🏰',
    planRequired: 'free',
    plan: 'free',
    previewColors: ['#1A1510', '#C9A84C', '#8B1E1E'],
    description: 'Pergaminho, runas e ouro de Tamriel.',
  },
  {
    name: 'clean',
    label: 'Clean',
    emoji: '✨',
    planRequired: 'free',
    plan: 'free',
    previewColors: ['#F8F9FC', '#6366F1', '#FFFFFF'],
    description: 'Vidro, luz e hierarquia premium.',
  },
  {
    name: 'naruto',
    label: 'Naruto',
    emoji: '🍥',
    planRequired: 'quarterly',
    plan: 'quarterly',
    previewColors: ['#0A0A0F', '#FF6B00', '#E8C84A'],
    description: 'Chakra, Konoha e missões ninja.',
  },
  {
    name: 'solo',
    label: 'Solo Leveling',
    emoji: '🗡️',
    planRequired: 'quarterly',
    plan: 'quarterly',
    previewColors: ['#050508', '#7B2FBE', '#00FFAA'],
    description: 'HUD do Sistema, portais e EXP.',
  },
  {
    name: 'cyberpunk',
    label: 'Cyberpunk',
    emoji: '🌃',
    planRequired: 'semiannual',
    plan: 'semiannual',
    previewColors: ['#0B0B12', '#FCEE0A', '#00F0FF'],
    description: 'Neon noturno da megalópole.',
  },
  {
    name: 'ghibli',
    label: 'Ghibli',
    emoji: '🍃',
    planRequired: 'semiannual',
    plan: 'semiannual',
    previewColors: ['#E8F2E4', '#3D7A4A', '#F4C56E'],
    description: 'Campo, vento e aquarela.',
  },
  {
    name: 'legendary',
    label: 'Legendary',
    emoji: '🐉',
    planRequired: 'annual',
    plan: 'annual',
    previewColors: ['#140C08', '#FFD76A', '#9B1D1D'],
    description: 'Exclusivo do pacto anual.',
  },
]
