export const THEMES = [
  {
    name: 'skyrim',
    label: 'Skyrim',
    emoji: '🏰',
    planRequired: 'free',
    plan: 'free',
    previewColors: ['#1A1510', '#C9A84C', '#8B1E1E'],
    description: 'Grimório aberto, auroras e Tamriel.',
  },
  {
    name: 'clean',
    label: 'Clean',
    emoji: '✨',
    planRequired: 'free',
    plan: 'free',
    previewColors: ['#0F1117', '#6366F1', '#F8FAFC'],
    description: 'Glassmorphism premium noturno.',
  },
  {
    name: 'naruto',
    label: 'Naruto',
    emoji: '🍥',
    planRequired: 'quarterly',
    plan: 'quarterly',
    previewColors: ['#1A0F05', '#FF6B00', '#E8C84A'],
    description: 'Mural da Hokage e selos de jutsu.',
  },
  {
    name: 'solo',
    label: 'Solo Leveling',
    emoji: '🗡️',
    planRequired: 'quarterly',
    plan: 'quarterly',
    previewColors: ['#050508', '#7B2FBE', '#00FFAA'],
    description: 'HUD de caçador, portal e EXP.',
  },
  {
    name: 'cyberpunk',
    label: 'Cyberpunk',
    emoji: '🌃',
    planRequired: 'semiannual',
    plan: 'semiannual',
    previewColors: ['#0B0B12', '#FCEE0A', '#00F0FF'],
    description: 'Neon noturno da megalópole.',
  },
  {
    name: 'ghibli',
    label: 'Ghibli',
    emoji: '🍃',
    planRequired: 'semiannual',
    plan: 'semiannual',
    previewColors: ['#E8F2E4', '#3D7A4A', '#F4C56E'],
    description: 'Campo, vento e aquarela.',
  },
  {
    name: 'legendary',
    label: 'Legendary',
    emoji: '🐉',
    planRequired: 'annual',
    plan: 'annual',
    previewColors: ['#140C08', '#FFD76A', '#9B1D1D'],
    description: 'Exclusivo do pacto anual.',
  },
]
